#!/usr/bin/env python3
"""Render the Homebrew Formula for a tagged slink release."""

from __future__ import annotations

import argparse
from pathlib import Path


def render(version: str, source_sha256: str) -> str:
    return f'''# This file is generated by kkensuke/slink. Do not edit it manually.
class Slink < Formula
  desc "Managed symbolic-link CLI for macOS"
  homepage "https://github.com/kkensuke/slink"
  url "https://github.com/kkensuke/slink/archive/refs/tags/v{version}.tar.gz"
  sha256 "{source_sha256}"
  license "MIT"

  depends_on "rust" => :build
  depends_on :macos

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/slink --version")

    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s
    target = testpath/"target"
    target.write "hello"
    link = testpath/"links/example"

    system bin/"slink", "--parents", target.to_s, link.to_s
    assert_predicate link, :symlink?
    assert_equal target.to_s, link.readlink.to_s
    system bin/"slink", "check", link.to_s
  end
end
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", required=True)
    parser.add_argument("--source-sha256", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    args.output.write_text(render(args.version, args.source_sha256), encoding="utf-8")


if __name__ == "__main__":
    main()
